### ISSUE TITLE
Se produjo un error de tipo E_ERROR en la línea 7 del archivo wp-content\plugins\gocuotas\includes\class-gocuotas.php. Mensaje de error: Uncaught Error: Class "WC_Payment_Gateway" not found

### ISSUE THREAD

**Issue by alipschutzsecuritize** [matesasesinos/gocuotas#2]
recibí un email de error de wordpress con este mensaje:

Se produjo un error de tipo E_ERROR en la línea 7 del archivo \httpdocs\wp-content\plugins\gocuotas\includes\class-gocuotas.php. Mensaje de error: Uncaught Error: Class "WC_Payment_Gateway" not found in \httpdocs\wp-content\plugins\gocuotas\includes\class-gocuotas.php:7
Stack trace:
#0 \httpdocs\wp-content\plugins\gocuotas\gocuotas.php(37): require_once()
#1 \httpdocs\wp-includes\class-wp-hook.php(324): WC_GoCuotas::includes()
#2 \httpdocs\wp-includes\class-wp-hook.php(348): WP_Hook->apply_filters()
#3 \httpdocs\wp-includes\plugin.php(517): WP_Hook->do_action()
#4 \httpdocs\wp-settings.php(555): do_action()
#5 \httpdocs\wp-config.php(85): require_once('...')
#6 \httpdocs\wp-load.php(50): require_once('...')
#7 \httpdocs\wp-admin\admin.php(34): require_once('...')
#8 \httpdocs\wp-admin\customize.php(13): require_once('...')
#9 {main}
  thrown

**Comment by matesasesinos** [comment]
@alipschutzsecuritize si podes pasame: versión de WP, versión de WC y versión de PHP de tu hosting. 

Ese error se da cuando el plugin no encuentra WooCommerce por lo cual es raro tu error.

Gracias.

**Comment by alipschutzsecuritize** [comment]
Por algun motivo que desconozco, se desintaló el WC de mi WP, si raro.
Aún asi, no debería fallar el WP completo, por eso.

Gracias,

**Comment by matesasesinos** [comment]
Si muy cierto, no tiene la validación de si esta instalado o no WC. Muchas gracias.
